### ISSUE TITLE
WEBUI > NETWORKS

### ISSUE THREAD

**Issue by ozburn** [cad/ovpm#55]
Hello Cad,
          After your help, i successfully log on WEBUI, i go to NETWORKS , and create Two ROUTED Networks..

OVPM_Users     10.0.0.1/24
OVPM_Servers  10.0.0.2/24

         No problem to create, but when i go to command line to list these NETWORKS ,  got a error...

root@stargate:/usr/local# ovpm net l
ERRO[0000] assoc users can not be fetched: rpc error: code = Unknown desc = validation error: `OVPM_Users` can only contain letters and numbers
root@stargate:/usr/local#

So, i go to delete the OVPM_Users and another issue , i can´t delete from WEBUI , maybe because the name OVPM_Users is not ok because contain not allowed char.,  will try to delete from command line..

Hope It Helps... and im not wrong in the way i use it...

My intention, was create 2 networks and after that,  isolate clients  on your own network , than  create more flexible rules in my firewalll based on networks.

Thanks..!!

**Comment by ozburn** [comment]
Can´t Remove from command line

root@stargate:/home/lucianol# ovpm net undef --net OVPM_Users
ERRO[0000] networks can not be deleted: rpc error: code = Unknown desc = validation error: `OVPN_Users` can only contain letters and numbers
root@stargate:/home/lucianol#

**Comment by ozburn** [comment]
I Believe i need to delete the database to init a new one, because i can´t delete the wrong networks names

How can i do that.? what is the file that hold all vpn configurations.?

Thanks

**Comment by cad** [comment]
@ozburn this is obviously a bug. I will fix it shortly and make a release.

**Comment by ozburn** [comment]
Thanks , i just stop de OVPMD service, deleted everything inside /var/db/ovpm , except directory "ccd" , start service ovpmd again , and do a init again,  all cleaned , i create the networks  like "NetUsers"  and no problema at all..!!  ;)  Thankyou.!

Just a comment , In Networks , what´s the difference between  ROUTED and SERVERNET..??

i really enjoing the way you build things, very organized and easy to understand, do thing´s,  with ovpm command is easy and good..!! Simple and very effective..!  of course.!  WEBUi  is more easy and its be graceful the way you are doing...  Much more easy and intuitive...  REally RoX.!  Glad to had discovered your project..!

**Comment by cad** [comment]
@ozburn those are OVPM [network types](https://github.com/cad/ovpm/wiki/Network-Management#network-types). 

For example, `ROUTE` type networks cause the route to be pushed to its associated users no matter what, and they don't cause any *iptables* rule modifications on the server.

On the other hand, `SERVERNET` type networks represent some network that is directly on the VPN server. When you **associate** a user to this type of network basically you give access to the user to reach out to the network, which is a network behind the VPN server. 
Behind the scenes, OVPM acts smartly and sets up the NAT for the defined network. And if the user has *No Push Gateway* configured, then OVPM also pushes routes to the user for these networks since otherwise it will be impossible for the clients to reach out to these networks.
