### ISSUE TITLE
Put existing server.conf in ovpm configuration

### ISSUE THREAD

**Issue by suknark** [cad/ovpm#66]
Hi
As i see now i can't put existing server.conf of my openvpn server.
Can you add option some like `ovpm vpn import --path=/tmp/server.conf`?

**Comment by cad** [comment]
What I think is **OVPM** doesn't need to understand **OpenVPN** config format directly since it has its own ways of defining configurations. 

So I believe it's not OVPM's job to make sense out of OpenVPN config format. It only generates them; for the underlying OpenVPN server to understand.

But it might be useful to have a separate tool for converting OpenVPN config format into OVPM config for the migration purposes.

After implementing #44, I can write a helper tool for that job. Something like `ovpm-import --from=/tmp/server.conf --out ovpm.conf`and then you can start ovpmd with the generated conf.
